/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#b1f0ce",
        "secondary-fixed-dim": "#c5c7c8",
        "inverse-surface": "#2d3135",
        "primary-container": "#1b4332",
        "error-container": "#ffdad6",
        "secondary": "#5c5f60",
        "inverse-primary": "#a5d0b9",
        "surface-dim": "#d7dadf",
        "surface-variant": "#e0e3e8",
        "background": "#f7f9ff",
        "on-tertiary-container": "#75b393",
        "error": "#ba1a1a",
        "on-primary-fixed": "#002114",
        "on-surface": "#181c20",
        "primary": "#012d1d",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "tertiary": "#002d1c",
        "secondary-fixed": "#e1e3e4",
        "on-secondary-fixed": "#191c1d",
        "secondary-container": "#e1e3e4",
        "primary-fixed-dim": "#a5d0b9",
        "surface-container-highest": "#e0e3e8",
        "on-tertiary-fixed-variant": "#0e5138",
        "tertiary-fixed-dim": "#95d4b3",
        "primary-fixed": "#c1ecd4",
        "surface-tint": "#3f6653",
        "on-secondary-fixed-variant": "#454748",
        "outline-variant": "#c1c8c2",
        "on-surface-variant": "#414844",
        "surface-bright": "#f7f9ff",
        "on-primary-container": "#86af99",
        "outline": "#717973",
        "inverse-on-surface": "#eef1f6",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#626566",
        "on-primary-fixed-variant": "#274e3d",
        "surface-container": "#ebeef3",
        "tertiary-container": "#00452e",
        "on-tertiary-fixed": "#002114",
        "on-background": "#181c20",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface": "#f7f9ff",
        "surface-container-high": "#e5e8ee",
        "surface-container-low": "#f1f4f9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        md: "16px",
        "gutter-mobile": "12px",
        xl: "32px",
        xs: "8px",
        "margin-mobile": "16px",
        lg: "24px",
        base: "4px",
      },
      fontFamily: {
        "body-lg": ["System"],
        "label-md": ["System"],
        "headline-md": ["System"],
        "headline-md-mobile": ["System"],
        "headline-sm": ["System"],
        "body-md": ["System"],
        "display-lg": ["System"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md-mobile": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
