"""Add RetailerReturn and Payment is_credit

Revision ID: 33d1cad9ad6f
Revises: 60da6b1317b1
Create Date: 2026-08-22 15:40:53.243461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d1cad9ad6f'
down_revision: Union[str, Sequence[str], None] = '60da6b1317b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer_returns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_bill_id', sa.Uuid(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('bird_count', sa.Integer(), nullable=True),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_bill_id'], ['delivery_bills.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_returns_created_at'), 'retailer_returns', ['created_at'], unique=False)
    op.create_index(op.f('ix_retailer_returns_retailer_id'), 'retailer_returns', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_retailer_returns_return_date'), 'retailer_returns', ['return_date'], unique=False)
    op.add_column('payments', sa.Column('is_credit', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'is_credit')
    op.drop_index(op.f('ix_retailer_returns_return_date'), table_name='retailer_returns')
    op.drop_index(op.f('ix_retailer_returns_retailer_id'), table_name='retailer_returns')
    op.drop_index(op.f('ix_retailer_returns_created_at'), table_name='retailer_returns')
    op.drop_table('retailer_returns')
    # ### end Alembic commands ###
