"""Add wholesale allocation ledger tracking

Revision ID: 36325e542abe
Revises: 5028779dda41
Create Date: 2026-08-27 23:04:31.939543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36325e542abe'
down_revision: Union[str, Sequence[str], None] = '5028779dda41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('mobile_number', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'DELIVERY', 'RETAILER', name='user_role', native_enum=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('permissions_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_retailer_id'), 'users', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('delivery_bill_items', sa.Column('box_charge', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.drop_index(op.f('ix_delivery_runs_farm_load_id'), table_name='delivery_runs')
    op.drop_constraint(op.f('delivery_runs_farm_load_id_fkey'), 'delivery_runs', type_='foreignkey')
    op.drop_column('delivery_runs', 'farm_load_id')
    op.add_column('farm_loads', sa.Column('empty_box_weight', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('farm_loads', sa.Column('weight_loss_kg', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('retailer_daily_order_items', sa.Column('locked_rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retailer_daily_order_items', 'locked_rate_per_kg')
    op.drop_column('farm_loads', 'weight_loss_kg')
    op.drop_column('farm_loads', 'empty_box_weight')
    op.add_column('delivery_runs', sa.Column('farm_load_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('delivery_runs_farm_load_id_fkey'), 'delivery_runs', 'farm_loads', ['farm_load_id'], ['id'])
    op.create_index(op.f('ix_delivery_runs_farm_load_id'), 'delivery_runs', ['farm_load_id'], unique=False)
    op.drop_column('delivery_bill_items', 'box_charge')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_retailer_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
