"""add item_id to farm loads

Revision ID: 5028779dda41
Revises: 57e2a56a5ea7
Create Date: 2026-08-27 21:22:06.381368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5028779dda41'
down_revision: Union[str, Sequence[str], None] = '57e2a56a5ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import os
    if os.environ.get("ALEMBIC_MODE") == "public":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_loads', sa.Column('item_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_farm_loads_item_id'), 'farm_loads', ['item_id'], unique=False)
    op.create_foreign_key(None, 'farm_loads', 'items', ['item_id'], ['id'])
    
    # Update existing records to use a default item
    op.execute(
        "UPDATE farm_loads SET item_id = (SELECT id FROM items LIMIT 1) WHERE item_id IS NULL"
    )
    
    op.alter_column('farm_loads', 'item_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    import os
    if os.environ.get("ALEMBIC_MODE") == "public":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farm_loads', type_='foreignkey')
    op.drop_index(op.f('ix_farm_loads_item_id'), table_name='farm_loads')
    op.drop_column('farm_loads', 'item_id')
    # ### end Alembic commands ###
