"""boxes_and_net_weight

Revision ID: 57e2a56a5ea7
Revises: b2c3d4e5f6g7
Create Date: 2026-08-27 20:50:27.340944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""boxes_and_net_weight

Revision ID: 57e2a56a5ea7
Revises: b2c3d4e5f6g7
Create Date: 2026-08-27 20:50:27.340944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e2a56a5ea7'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import os
    if os.environ.get("ALEMBIC_MODE") == "public":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_stop_items', sa.Column('delivered_boxes', sa.Integer(), nullable=True))
    op.add_column('delivery_stop_items', sa.Column('gross_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('delivery_stop_items', sa.Column('empty_box_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True))
    op.create_unique_constraint('uq_delivery_stop_run_retailer', 'delivery_stops', ['delivery_run_id', 'retailer_id'])
    op.alter_column('retailer_daily_order_items', 'requested_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('retailer_item_rates', 'item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_retailer_item_rates_item_id'), 'retailer_item_rates', ['item_id'], unique=False)
    op.create_unique_constraint('uq_retailer_item_rate', 'retailer_item_rates', ['retailer_id', 'item_id', 'effective_from'])
    op.create_foreign_key('fk_retailer_item_rates_item_id', 'retailer_item_rates', 'items', ['item_id'], ['id'])
    op.create_index(op.f('ix_retailer_returns_item_id'), 'retailer_returns', ['item_id'], unique=False)
    op.create_foreign_key('fk_retailer_returns_item_id', 'retailer_returns', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    import os
    if os.environ.get("ALEMBIC_MODE") == "public":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_retailer_returns_item_id', 'retailer_returns', type_='foreignkey')
    op.drop_index(op.f('ix_retailer_returns_item_id'), table_name='retailer_returns')
    op.drop_constraint('fk_retailer_item_rates_item_id', 'retailer_item_rates', type_='foreignkey')
    op.drop_constraint('uq_retailer_item_rate', 'retailer_item_rates', type_='unique')
    op.drop_index(op.f('ix_retailer_item_rates_item_id'), table_name='retailer_item_rates')
    op.alter_column('retailer_item_rates', 'item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('retailer_daily_order_items', 'requested_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.drop_constraint('uq_delivery_stop_run_retailer', 'delivery_stops', type_='unique')
    op.drop_column('delivery_stop_items', 'empty_box_weight_kg')
    op.drop_column('delivery_stop_items', 'gross_weight_kg')
    op.drop_column('delivery_stop_items', 'delivered_boxes')
    # ### end Alembic commands ###
