"""Add item_id and total_amount to retailer_returns

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-08-25 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6g7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retailer_returns', sa.Column('item_id', UUID(as_uuid=True), nullable=True))
    op.add_column('retailer_returns', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.create_index(op.f('ix_retailer_returns_item_id'), 'retailer_returns', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retailer_returns_item_id'), table_name='retailer_returns')
    op.drop_column('retailer_returns', 'total_amount')
    op.drop_column('retailer_returns', 'item_id')
    # ### end Alembic commands ###
