"""add_order_sequence_and_number

Revision ID: f08f9cc44324
Revises: 
Create Date: 2026-08-24 10:50:09.422240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08f9cc44324'
down_revision: Union[str, Sequence[str], None] = '33d1cad9ad6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', name='uq_order_sequence_year')
    )
    op.add_column('retailer_daily_orders', sa.Column('order_number', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_retailer_daily_orders_order_number'), 'retailer_daily_orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retailer_daily_orders_order_number'), table_name='retailer_daily_orders')
    op.drop_column('retailer_daily_orders', 'order_number')
    op.drop_table('order_sequences')
    # ### end Alembic commands ###
