"""Init public tables

Revision ID: 2422fde3c720
Revises: 
Create Date: 2026-08-22 11:17:04.372564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2422fde3c720'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table: str) -> bool:
    bind = op.get_bind()
    return bind.dialect.has_table(bind, table, schema="public")


def _has_index(table: str, idx: str) -> bool:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    try:
        return any(i["name"] == idx for i in insp.get_indexes(table, schema="public"))
    except Exception:
        return False


def upgrade() -> None:
    """Upgrade schema — idempotent: skips tables/indexes that already exist (handles manage.py setup case)."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('organizations'):
        op.create_table('organizations',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=80), nullable=False),
        sa.Column('schema_name', sa.String(length=63), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('schema_name')
        )
    if not _has_index('organizations', 'ix_organizations_created_at'):
        op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    if not _has_index('organizations', 'ix_organizations_slug'):
        op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    if not _has_table('user_auth_index'):
        op.create_table('user_auth_index',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('username_lower', sa.String(length=80), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=True),
        sa.Column('schema_name', sa.String(length=63), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_index('user_auth_index', 'ix_user_auth_index_created_at'):
        op.create_index(op.f('ix_user_auth_index_created_at'), 'user_auth_index', ['created_at'], unique=False)
    if not _has_index('user_auth_index', 'ix_user_auth_index_organization_id'):
        op.create_index(op.f('ix_user_auth_index_organization_id'), 'user_auth_index', ['organization_id'], unique=False)
    if not _has_index('user_auth_index', 'ix_user_auth_index_username_lower'):
        op.create_index(op.f('ix_user_auth_index_username_lower'), 'user_auth_index', ['username_lower'], unique=True)
    if not _has_table('users'):
        op.create_table('users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=120), nullable=True),
        sa.Column('mobile_number', sa.String(length=30), nullable=True),
        sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'DELIVERY', 'RETAILER', name='user_role', native_enum=False), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=True),
        sa.Column('retailer_id', sa.Uuid(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('permissions_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_index('users', 'ix_users_created_at'):
        op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    if not _has_index('users', 'ix_users_organization_id'):
        op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    if not _has_index('users', 'ix_users_retailer_id'):
        op.create_index(op.f('ix_users_retailer_id'), 'users', ['retailer_id'], unique=False)
    if not _has_index('users', 'ix_users_username'):
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_retailer_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_auth_index_username_lower'), table_name='user_auth_index')
    op.drop_index(op.f('ix_user_auth_index_organization_id'), table_name='user_auth_index')
    op.drop_index(op.f('ix_user_auth_index_created_at'), table_name='user_auth_index')
    op.drop_table('user_auth_index')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
