"""Add bird_size to retailer_daily_orders

Revision ID: d6944ad5e8b6
Revises: dcfcaa07b246
Create Date: 2026-08-18 10:37:41.080799

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6944ad5e8b6'
down_revision: Union[str, Sequence[str], None] = 'dcfcaa07b246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_loads', sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('farm_loads', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('farm_loads', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('farm_loads', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('farms', sa.Column('owner_name', sa.String(length=120), nullable=True))
    op.add_column('farms', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('farms', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('retailer_daily_orders', sa.Column('bird_size', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retailer_daily_orders', 'bird_size')
    op.drop_column('farms', 'capacity')
    op.drop_column('farms', 'address')
    op.drop_column('farms', 'owner_name')
    op.drop_column('farm_loads', 'payment_method')
    op.drop_column('farm_loads', 'paid_amount')
    op.drop_column('farm_loads', 'total_amount')
    op.drop_column('farm_loads', 'rate_per_kg')
    # ### end Alembic commands ###
