"""Init public

Revision ID: dcfcaa07b246
Revises: 
Create Date: 2026-08-10 12:56:41.098704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfcaa07b246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', name='uq_bill_sequence_year')
    )
    op.create_index(op.f('ix_bill_sequences_created_at'), 'bill_sequences', ['created_at'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_created_at'), 'farms', ['created_at'], unique=False)
    op.create_table('org_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('weight_loss_warn_pct', sa.Numeric(precision=8, scale=2), server_default=sa.text('2.00'), nullable=False),
    sa.Column('weight_loss_alert_pct', sa.Numeric(precision=8, scale=2), server_default=sa.text('5.00'), nullable=False),
    sa.Column('enforce_credit_limit', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_settings_created_at'), 'org_settings', ['created_at'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('schema_name', sa.String(length=63), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_name')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('retailers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('shop_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('alternate_phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('credit_balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('route_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('preferred_delivery_time', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailers_created_at'), 'retailers', ['created_at'], unique=False)
    op.create_table('user_auth_index',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username_lower', sa.String(length=80), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('schema_name', sa.String(length=63), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_lower', 'organization_id', name='uq_auth_index_user_org')
    )
    op.create_index(op.f('ix_user_auth_index_created_at'), 'user_auth_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_auth_index_organization_id'), 'user_auth_index', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_auth_index_username_lower'), 'user_auth_index', ['username_lower'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'DELIVERY', 'RETAILER', name='user_role', native_enum=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('permissions_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_retailer_id'), 'users', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_vehicles_created_at'), 'vehicles', ['created_at'], unique=False)
    op.create_table('farm_loads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('load_date', sa.Date(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=40), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('driver_user_id', sa.Uuid(), nullable=True),
    sa.Column('loaded_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('bird_count', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_TRANSIT', 'CLOSED', name='farm_load_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_loads_created_at'), 'farm_loads', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_loads_load_date'), 'farm_loads', ['load_date'], unique=False)
    op.create_table('retailer_daily_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PLACED', 'ACKNOWLEDGED', 'PARTIAL', 'FULFILLED', 'CANCELLED', name='order_status', native_enum=False), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'order_date', name='uq_retailer_daily_order')
    )
    op.create_index(op.f('ix_retailer_daily_orders_created_at'), 'retailer_daily_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_retailer_daily_orders_order_date'), 'retailer_daily_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_retailer_daily_orders_retailer_id'), 'retailer_daily_orders', ['retailer_id'], unique=False)
    op.create_table('retailer_item_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_item_rates_created_at'), 'retailer_item_rates', ['created_at'], unique=False)
    op.create_index(op.f('ix_retailer_item_rates_retailer_id'), 'retailer_item_rates', ['retailer_id'], unique=False)
    op.create_table('delivery_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_load_id', sa.Uuid(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='delivery_run_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['farm_load_id'], ['farm_loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_runs_created_at'), 'delivery_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_delivery_runs_farm_load_id'), 'delivery_runs', ['farm_load_id'], unique=False)
    op.create_index(op.f('ix_delivery_runs_run_date'), 'delivery_runs', ['run_date'], unique=False)
    op.create_table('delivery_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_run_id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('daily_order_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('ordered_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('delivered_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'WEIGHED', 'BILLED', 'SKIPPED', name='delivery_stop_status', native_enum=False), nullable=False),
    sa.Column('weighed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scale_device_id', sa.String(length=120), nullable=True),
    sa.Column('weight_override_reason', sa.String(length=500), nullable=True),
    sa.Column('delivered_bird_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['daily_order_id'], ['retailer_daily_orders.id'], ),
    sa.ForeignKeyConstraint(['delivery_run_id'], ['delivery_runs.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_stops_created_at'), 'delivery_stops', ['created_at'], unique=False)
    op.create_index(op.f('ix_delivery_stops_delivery_run_id'), 'delivery_stops', ['delivery_run_id'], unique=False)
    op.create_index(op.f('ix_delivery_stops_retailer_id'), 'delivery_stops', ['retailer_id'], unique=False)
    op.create_table('trip_weight_losses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_load_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_run_id', sa.Uuid(), nullable=False),
    sa.Column('loaded_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('delivered_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('loss_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('loss_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_run_id'], ['delivery_runs.id'], ),
    sa.ForeignKeyConstraint(['farm_load_id'], ['farm_loads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_run_id', name='uq_trip_weight_loss_run')
    )
    op.create_index(op.f('ix_trip_weight_losses_created_at'), 'trip_weight_losses', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_weight_losses_farm_load_id'), 'trip_weight_losses', ['farm_load_id'], unique=False)
    op.create_table('delivery_bills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bill_number', sa.String(length=32), nullable=False),
    sa.Column('checkout_id', sa.String(length=64), nullable=False),
    sa.Column('delivery_stop_id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_payment', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('upi_payment', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('print_status', sa.Enum('PENDING', 'PRINTED', 'FAILED', 'SKIPPED', name='print_status', native_enum=False), nullable=False),
    sa.Column('whatsapp_shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_stop_id'], ['delivery_stops.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number', name='uq_delivery_bill_number'),
    sa.UniqueConstraint('checkout_id', name='uq_delivery_bill_checkout'),
    sa.UniqueConstraint('delivery_stop_id')
    )
    op.create_index(op.f('ix_delivery_bills_bill_date'), 'delivery_bills', ['bill_date'], unique=False)
    op.create_index(op.f('ix_delivery_bills_bill_number'), 'delivery_bills', ['bill_number'], unique=False)
    op.create_index(op.f('ix_delivery_bills_checkout_id'), 'delivery_bills', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_delivery_bills_created_at'), 'delivery_bills', ['created_at'], unique=False)
    op.create_index(op.f('ix_delivery_bills_retailer_id'), 'delivery_bills', ['retailer_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_bill_id', sa.Uuid(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('upi_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.Enum('RECEIVED', 'ADJUSTMENT', name='payment_type', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_bill_id'], ['delivery_bills.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_retailer_id'), 'payments', ['retailer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_retailer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_delivery_bills_retailer_id'), table_name='delivery_bills')
    op.drop_index(op.f('ix_delivery_bills_created_at'), table_name='delivery_bills')
    op.drop_index(op.f('ix_delivery_bills_checkout_id'), table_name='delivery_bills')
    op.drop_index(op.f('ix_delivery_bills_bill_number'), table_name='delivery_bills')
    op.drop_index(op.f('ix_delivery_bills_bill_date'), table_name='delivery_bills')
    op.drop_table('delivery_bills')
    op.drop_index(op.f('ix_trip_weight_losses_farm_load_id'), table_name='trip_weight_losses')
    op.drop_index(op.f('ix_trip_weight_losses_created_at'), table_name='trip_weight_losses')
    op.drop_table('trip_weight_losses')
    op.drop_index(op.f('ix_delivery_stops_retailer_id'), table_name='delivery_stops')
    op.drop_index(op.f('ix_delivery_stops_delivery_run_id'), table_name='delivery_stops')
    op.drop_index(op.f('ix_delivery_stops_created_at'), table_name='delivery_stops')
    op.drop_table('delivery_stops')
    op.drop_index(op.f('ix_delivery_runs_run_date'), table_name='delivery_runs')
    op.drop_index(op.f('ix_delivery_runs_farm_load_id'), table_name='delivery_runs')
    op.drop_index(op.f('ix_delivery_runs_created_at'), table_name='delivery_runs')
    op.drop_table('delivery_runs')
    op.drop_index(op.f('ix_retailer_item_rates_retailer_id'), table_name='retailer_item_rates')
    op.drop_index(op.f('ix_retailer_item_rates_created_at'), table_name='retailer_item_rates')
    op.drop_table('retailer_item_rates')
    op.drop_index(op.f('ix_retailer_daily_orders_retailer_id'), table_name='retailer_daily_orders')
    op.drop_index(op.f('ix_retailer_daily_orders_order_date'), table_name='retailer_daily_orders')
    op.drop_index(op.f('ix_retailer_daily_orders_created_at'), table_name='retailer_daily_orders')
    op.drop_table('retailer_daily_orders')
    op.drop_index(op.f('ix_farm_loads_load_date'), table_name='farm_loads')
    op.drop_index(op.f('ix_farm_loads_created_at'), table_name='farm_loads')
    op.drop_table('farm_loads')
    op.drop_index(op.f('ix_vehicles_created_at'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_retailer_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_auth_index_username_lower'), table_name='user_auth_index')
    op.drop_index(op.f('ix_user_auth_index_organization_id'), table_name='user_auth_index')
    op.drop_index(op.f('ix_user_auth_index_created_at'), table_name='user_auth_index')
    op.drop_table('user_auth_index')
    op.drop_index(op.f('ix_retailers_created_at'), table_name='retailers')
    op.drop_table('retailers')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_org_settings_created_at'), table_name='org_settings')
    op.drop_table('org_settings')
    op.drop_index(op.f('ix_farms_created_at'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_bill_sequences_created_at'), table_name='bill_sequences')
    op.drop_table('bill_sequences')
    # ### end Alembic commands ###
